integrate game details page design
wanned/karmine-corp-app pull request #25
Opened 2024-01-18 00:57 UTC by bdauphouy

2024-01-18 11:57 UTC, arthur-fontaine requested changes

2024-01-18 11:57 UTC, arthur-fontaine commented on src/screens/game-details-modal/components/types/player.ts
> +  role: 'top' | 'jungle' | 'mid' | 'adc' | 'support';
A player has not necessarily a role, and it can be any string

2024-01-18 11:57 UTC, arthur-fontaine commented on src/screens/game-details-modal/components/types/player.ts
> +  picture: string;
A player has not necessarily a picture. If he has no picture, show this.
<img width="125" alt="Capture d’écran 2024-01-18 à 12 56 39" src="https://github.com/wanned/karmine-corp-app/assets/57626613/204cdc06-d19d-4835-a799-17d82d5027f0">

2024-01-26 13:55 UTC, arthur-fontaine requested changes

2024-01-26 13:55 UTC, arthur-fontaine commented on src/screens/game-details-modal/index.tsx
> +export const GameDetailsModal = React.memo(({ route: { params } }: GameDetailsModalProps) => {
This does not scroll

2024-01-26 13:55 UTC, arthur-fontaine commented on src/screens/game-details-modal/components/lol-games.tsx
> +        <Typographies.Body color={theme.colors.subtleForeground}>{duration}</Typographies.Body>
Those seem to not be correctly aligned.

2024-01-26 13:55 UTC, arthur-fontaine commented on src/shared/types/data/Matchs.ts
> +  duration: string;
The duration should be a number of seconds, and it is formatted inside the component.

2024-01-29 18:51 UTC, thierrymgn requested changes
We have this error in other modals now `VirtualizedListsshould never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`

2024-01-29 20:46 UTC, thierrymgn approved these changes

2024-01-29 20:56 UTC, merged